name: Makefile CI

on:
  push:
    branches: [ main , meta1]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build All
      run: make
